#ifndef FIRMWARE_VERSION_H
#define FIRMWARE_VERSION_H

#define FIRMWARE_VERSION_MAJOR 	1
#define FIRMWARE_VERSION_MINOR	0
#define FIRMWARE_VERSION_PATCH	0
#define FIRMWARE_VERSION 		(((FIRMWARE_VERSION_MAJOR<<16) & 0xff0000) | ((FIRMWARE_VERSION_MINOR<<8) & 0xff00) | (FIRMWARE_VERSION_PATCH & 0xff))

#endif